# fly.toml app configuration file generated for bumpwin-demo on 2025-05-21T10:30:34+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bumpwin-demo"
primary_region = "nrt"

[build]
dockerfile = "apps/cmd/Dockerfile"

[env]
PORT = "8080"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8080
min_machines_running = 0
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024
