import type { MemeMetadata } from "@workspace/types";
import { MEME_IDS } from "./memeIds";

export const mockmemes: MemeMetadata[] = [
  {
    id: MEME_IDS.LAG,
    symbol: "LAG",
    name: "Lag Girl",
    description: "lagging since 2020",
    iconUrl: "/images/mockmemes/LAG.jpg",
  },
  {
    id: MEME_IDS.MOCAT,
    symbol: "MOCAT",
    name: "Mocaccino Cat",
    description: "just knocked over $3B in TVL. still no regrets.",
    iconUrl: "/images/mockmemes/MOCAT.jpg",
  },
  {
    id: MEME_IDS.BUN,
    symbol: "BUN",
    name: "Bun Protocol",
    description: "🥟 one bite = full degen enlightenment",
    iconUrl: "/images/mockmemes/BUN.webp",
  },
  {
    id: MEME_IDS.COLA,
    symbol: "COLA",
    name: "Koala Kash",
    description: "sleeping through dips, awake for pumps 🌳",
    iconUrl: "/images/mockmemes/COLA.png",
  },
  {
    id: MEME_IDS.ANTS,
    symbol: "ANTS",
    name: "Gigants Protocol",
    description: "when all ants have diamond hands",
    iconUrl: "/images/mockmemes/ANTS.webp",
  },
  {
    id: MEME_IDS.JELL,
    symbol: "JELL",
    name: "Jelly Cube",
    description: "wobbling to ATH",
    iconUrl: "/images/mockmemes/JELL.png",
  },
  {
    id: MEME_IDS.RACC,
    symbol: "RACC",
    name: "Trash Raccoon",
    description: "one degen's rug is another raccoon's treasure",
    iconUrl: "/images/mockmemes/RACC.webp",
  },
  {
    id: MEME_IDS.CHEDER,
    symbol: "CHEDER",
    name: "Big Cheder",
    description: "more cheese = more profits 🧀",
    iconUrl: "/images/mockmemes/CHEDER.png",
  },
  {
    id: MEME_IDS.DITT,
    symbol: "DITT",
    name: "Dittoscream",
    description: "melting shorts since genesis",
    iconUrl: "/images/mockmemes/DITT.png",
  },
  {
    id: MEME_IDS.HAHA,
    symbol: "HAHA",
    name: "HaHa Protocol",
    description: "laugh now, moon later",
    iconUrl: "/images/mockmemes/HAHA.webp",
  },
  {
    id: MEME_IDS.MONKE,
    symbol: "MONKE",
    name: "Based Monke",
    description: "monkey see gains, monkey hold forever",
    iconUrl: "/images/mockmemes/MONKE.jpeg",
  },
  {
    id: MEME_IDS.YAKIU,
    symbol: "YAKIU",
    name: "Yakiu",
    description: "home run tokenomics, strike out bears",
    iconUrl: "/images/mockmemes/YAKIU.png",
  },
  {
    id: MEME_IDS.LILCUTE,
    symbol: "LILCUTE",
    name: "Lil Cute",
    description: "too cute to dump, too small to fail",
    iconUrl: "/images/mockmemes/LILCUTE.gif",
  },
  {
    id: MEME_IDS.HIGHER,
    symbol: "HIGHER",
    name: "Higher Protocol",
    description: "only direction = moon",
    iconUrl: "/images/mockmemes/HIGHER.webp",
  },
  {
    id: MEME_IDS.HOGGY,
    symbol: "HOGGY",
    name: "Hedgehog Finance",
    description: "spiky gains, cozy vibes",
    iconUrl: "/images/mockmemes/HOGGY.webp",
  },
  {
    id: MEME_IDS.WAGMI,
    symbol: "WAGMI",
    name: "WAGMI Cat",
    description: "we all gonna meow it",
    iconUrl: "/images/mockmemes/WAGMI.png",
  },
  {
    id: MEME_IDS.GLOSER,
    symbol: "GLOSER",
    name: "Gloser Token",
    description: "getting closer to 100x every day",
    iconUrl: "/images/mockmemes/GLOSER.png",
  },
  {
    id: MEME_IDS.SAT,
    symbol: "SAT",
    name: "Satisfied Seal",
    description: "satisfied with 1000x minimum",
    iconUrl: "/images/mockmemes/SAT.webp",
  },
  {
    id: MEME_IDS.COONYE,
    symbol: "COONYE",
    name: "CoonYe Coin",
    description: "the hero we didn't deserve",
    iconUrl: "/images/mockmemes/COONYE.jpg",
  },
  {
    id: MEME_IDS.SMUG,
    symbol: "SMUG",
    name: "Smug Protocol",
    description: "knowing something the market doesn't",
    iconUrl: "/images/mockmemes/SMUG.webp",
  },
  {
    id: MEME_IDS.RUGT,
    symbol: "RUGT",
    name: "Rug Token",
    description: "the rug that rugs other rugs",
    iconUrl: "/images/mockmemes/RUGT.png",
  },
  {
    id: MEME_IDS.LOSER,
    symbol: "LOSER",
    name: "Loser Coin",
    description: "losing so hard we're winning",
    iconUrl: "/images/mockmemes/LOSER.png",
  },
  {
    id: MEME_IDS.DOOD,
    symbol: "DOOD",
    name: "Doodle Dood",
    description: "professionally unprofessional",
    iconUrl: "/images/mockmemes/DOOD.png",
  },
  {
    id: MEME_IDS.TREX,
    symbol: "TREX",
    name: "T-Rex Arms",
    description: "can't sell with these tiny hands",
    iconUrl: "/images/mockmemes/TREX.png",
  },
  {
    id: MEME_IDS.YELL,
    symbol: "YELL",
    name: "Yellow Protocol",
    description: "screaming buy signals since day 1",
    iconUrl: "/images/mockmemes/YELL.png",
  },
  {
    id: MEME_IDS.CHILLKITYY,
    symbol: "CHILLKITYY",
    name: "Chill Kitty",
    description: "too chill to care about dips",
    iconUrl: "/images/mockmemes/CHILLKITYY.webp",
  },
];

export const mockMemeMetadata = mockmemes;
